name: CI - Docker Compose & Integração & Desempenho

on:
  push:
    branches: RNFTests

jobs:
  login:
    runs-on: ubuntu-latest

    services:
      docker: docker:24.0.5-cli
      options: --privileged

    steps:
      - name: Criar .env para o backend
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> backend/.env
          echo "SECRET_KEY_LOGIN=${{ secrets.SECRET_KEY_LOGIN }}" >> backend/.env
          echo "SECRET_KEY_SIGNUP=${{ secrets.SECRET_KEY_SIGNUP }}" >> backend/.env
          echo "SECRET_KEY_RECOVERY=${{ secrets.SECRET_KEY_RECOVERY }}" >> backend/.env
          echo "ALGORITHM=${{ secrets.ALGORITHM }}" >> backend/.env
          echo "EXPIRE_MINUTES_LOGIN=${{ secrets.EXPIRE_MINUTES_LOGIN }}" >> backend/.env
          echo "EXPIRE_MINUTES_SIGNUP=${{ secrets.EXPIRE_MINUTES_SIGNUP }}" >> backend/.env
          echo "UPLOAD_DIR_ORCAMENTO=${{ secrets.UPLOAD_DIR_ORCAMENTO }}" >> backend/.env
          echo "UPLOAD_DIR_RECURSO=${{ secrets.UPLOAD_DIR_RECURSO }}" >> backend/.env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> backend/.env
      - 
        name: Checkout do repositório
        uses: actions/checkout@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Instalar Docker Compose
        uses: docker/setup-compose-action@v2
      -
        name: Up os containers com Docker Compose
        run: docker-compose up -d --build
      -
        name: Esperar que os serviços estejam prontos
        run: |
            echo "Aguardar 20 segundos para garantir que a API está ativa..."
            sleep 20
      -
        name: Instalar dependências Python
        run: |
            python3 -v venv venv
            source venv/bin/activate
            pip install httpx pytest
      -
        name: Correr testes de conexão e performance
        run: |
            pytest backend/tests/test_performance.py
